### ISSUE TITLE
Leaving this here as I will forget

### ISSUE THREAD

**Issue by JoeDec** [T-Wainwright/zCFD_Utils#3]
In multiscale.cpp, sample_control_points:

Lines 54 & 56:
my_kd_tree_t X_tree(3, std::cref(X), 20);

std::vector<double> query_pt(3);

Are assuming 3D data? 

Ctrl+F 3 , replace with Ndim  = X.cols() ?

**Comment by T-Wainwright** [comment]
Addressed in commit #6328467
